# fly.toml app configuration file generated for ratehive-api on 2023-06-23T09:00:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ratehive-api"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
